//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYSZNELAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jedzonko
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jedzonko()
        {
            this.Zamówienie = new HashSet<Zamówienie>();
        }
    
        public int Id { get; set; }
        public int Id_Restauracji { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Restauracja Restauracja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamówienie> Zamówienie { get; set; }
    }
}
