//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYSZNELAST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauracjaEntities : DbContext
    {
        public RestauracjaEntities()
            : base("name=RestauracjaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jedzonko> Jedzonko { get; set; }
        public virtual DbSet<Restauracja> Restauracja { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Użytkownicy> Użytkownicy { get; set; }
        public virtual DbSet<Zamówienie> Zamówienie { get; set; }
    }
}
