//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYSZNELAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Użytkownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Użytkownicy()
        {
            this.Zamówienie = new HashSet<Zamówienie>();
        }
    
        public int Id { get; set; }
        public string Nazwa_Użytkownika { get; set; }
        public string Hasło { get; set; }
        public string Adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamówienie> Zamówienie { get; set; }
    }
}
