//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYSZNELAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienie()
        {
            this.Jedzonko = new HashSet<Jedzonko>();
        }
    
        public int Id { get; set; }
        public int Id_Użytkownika { get; set; }
    
        public virtual Użytkownicy Użytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jedzonko> Jedzonko { get; set; }
    }
}
